---
title: "Covariance matrix estimation issue"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## LW vs fit_mvt

## The True underlying correlation  matrix


```{r cars}
pacman::p_load(MCmarket, tidyverse, ggcorrplot, lubridate, RiskPortfolios)
corr_3 <- gen_corr(D = 50, clusters = "non-overlapping", num_clusters = 5)
corr_3 %>% ggcorrplot(hc.order = TRUE, title = "Five Clusters")
```

## Correlation matrix estiated with 100 periods

```{r , echo=FALSE}
load("data/market_3_temp.rda")

market %>%
    filter(date < first(date) %m+% days(100) &
               date >= first(date)) %>%
    spread(Asset, Return) %>% select(-date) %>%
    fitHeavyTail::fit_mvt(.) %>% .$cov %>% cov2cor() %>% ggcorrplot::ggcorrplot(title = "100 periods")


market %>%
    filter(date < first(date) %m+% days(100) &
               date >= first(date)) %>%
    spread(Asset, Return) %>% select(-date) %>% as.matrix() %>% 
  RiskPortfolios::covEstimation(control = list(type = "lw")) %>% cov2cor() %>% ggcorrplot::ggcorrplot(title = "100 periods-lw")

```

## Correlation estiated with 150 periods
```{r , echo=FALSE}
market %>%
    filter(date < first(date) %m+% days(150) &
               date >= first(date)) %>%
    spread(Asset, Return) %>% select(-date) %>%
    fitHeavyTail::fit_mvt() %>% .$cov %>% cov2cor() %>% ggcorrplot::ggcorrplot(title = "150 periods")

market %>%
    filter(date < first(date) %m+% days(150) &
               date >= first(date)) %>%
    spread(Asset, Return) %>% select(-date) %>% as.matrix() %>% 
  RiskPortfolios::covEstimation(control = list(type = "lw")) %>% cov2cor() %>% ggcorrplot::ggcorrplot(title = "150 periods-lw")

```

## Correlation estiated with 200 periods
```{r , echo=FALSE}
market %>%
    filter(date < first(date) %m+% days(200) &
               date >= first(date)) %>%
    spread(Asset, Return) %>% select(-date) %>%
    fitHeavyTail::fit_mvt() %>% .$cov %>% cov2cor() %>% ggcorrplot::ggcorrplot(title = "200 periods")

market %>%
    filter(date < first(date) %m+% days(200) &
               date >= first(date)) %>%
    spread(Asset, Return) %>% select(-date) %>% as.matrix() %>% 
  RiskPortfolios::covEstimation(control = list(type = "lw")) %>% cov2cor() %>% ggcorrplot::ggcorrplot(title = "200 periods-lw")

```

## Which is better?

eyeballing it indicates that the difference is minor. The lw does seem somewhat less noisy though.  Please tell me which one you think I should use. Thanks again. 